# Generated by Django 6.0.5 on 2026-06-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='exhibitions/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Предстоящая'), ('current', 'Текущая'), ('past', 'Прошедшая')], default='upcoming', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('artists', models.ManyToManyField(blank=True, to='artists.artist')),
                ('artworks', models.ManyToManyField(blank=True, to='artists.artwork')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
