# Generated by Django 6.0.5 on 2026-07-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0015_artwork_is_published'),
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='workshops',
            field=models.ManyToManyField(blank=True, to='artists.workshop'),
        ),
    ]
