# Generated by Django 6.0.5 on 2026-07-18 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0002_exhibition_workshops'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exhibitions/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись (необязательно)')),
                ('order', models.IntegerField(default=0)),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exhibitions.exhibition')),
            ],
            options={
                'verbose_name': 'Фото с выставки',
                'verbose_name_plural': 'Фото с выставки',
                'ordering': ['order'],
            },
        ),
    ]
