# Generated by Django 6.0.5 on 2026-07-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0003_exhibitionimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='artworks',
        ),
    ]
