# Generated by Django 6.0.5 on 2026-06-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='shop/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KGS', max_length=10)),
                ('category', models.CharField(choices=[('artwork', 'Работа'), ('print', 'Принт'), ('book', 'Книга / Каталог'), ('merchandise', 'Сувенир')], default='artwork', max_length=30)),
                ('artist_name', models.CharField(blank=True, max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Магазин',
                'ordering': ['-created_at'],
            },
        ),
    ]
