# Generated by Django 6.0.6 on 2026-06-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='quote',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
