# Generated by Django 6.0.6 on 2026-06-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_workshop_workshopmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
