# Generated by Django 6.0.6 on 2026-06-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_workshop_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
