# Generated by Django 6.0.6 on 2026-06-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_artist_qr_code_workshop_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='weight',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
