# Generated by Django 6.0.6 on 2026-06-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_artwork_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
