# Generated by Django 6.0.5 on 2026-07-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_artworkimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='designed_by',
            field=models.ManyToManyField(blank=True, related_name='designed_artworks', to='artists.artist'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='made_by',
            field=models.ManyToManyField(blank=True, related_name='made_artworks', to='artists.artist'),
        ),
    ]
