# Generated by Django 6.0.5 on 2026-07-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_artwork_designed_by_artwork_made_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='designed_by_workshops',
            field=models.ManyToManyField(blank=True, related_name='designed_artworks', to='artists.workshop'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='made_by_workshops',
            field=models.ManyToManyField(blank=True, related_name='made_artworks', to='artists.workshop'),
        ),
    ]
