# Generated by Django 6.0.5 on 2026-07-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0010_artwork_designed_by_workshops_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artist',
        ),
    ]
