# Generated by Django 6.0.5 on 2026-07-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0010_artwork_designed_by_workshops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('available', 'В наличии'), ('sold', 'Продано'), ('reserved', 'Зарезервировано')], default='available', max_length=20),
        ),
    ]
