# Generated by Django 6.0.5 on 2026-07-02 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0011_artwork_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopmember',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_memberships', to='artists.artist'),
        ),
        migrations.AddField(
            model_name='workshopmember',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
