# Generated by Django 6.0.5 on 2026-07-07 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0011_remove_artwork_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='subtitle',
        ),
    ]
