# Generated by Django 6.0.5 on 2026-07-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0011_remove_artwork_artist'),
        ('artists', '0012_workshopmember_artist_workshopmember_role'),
    ]

    operations = [
    ]
