# Generated by Django 6.0.5 on 2026-07-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0012_remove_workshop_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AddField(
            model_name='workshopmember',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
    ]
