# Generated by Django 6.0.5 on 2026-07-14 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0013_artist_is_published_workshop_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название серии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover_image', models.ImageField(blank=True, help_text='Если не задано, то возьмётся первая работа серии', upload_to='series/', verbose_name='Обложка')),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('artists', models.ManyToManyField(blank=True, related_name='series', to='artists.artist', verbose_name='Мастера')),
                ('workshops', models.ManyToManyField(blank=True, related_name='series', to='artists.workshop', verbose_name='Мастерские')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='artists.series', verbose_name='Серия'),
        ),
    ]
