# Generated by Django 6.0.6 on 2026-07-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0013_merge_20260706_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workshopmember',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='workshopmember',
            name='role',
        ),
    ]
