# Generated by Django 6.0.5 on 2026-07-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0014_series_artwork_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
    ]
