# Generated by Django 6.0.5 on 2026-07-06 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0014_remove_artwork_status_remove_workshopmember_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('available', 'В наличии'), ('sold', 'Продано'), ('reserved', 'Зарезервировано')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='workshopmember',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_memberships', to='artists.artist'),
        ),
        migrations.AddField(
            model_name='workshopmember',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
