# Generated by Django 6.0.5 on 2026-07-23 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0015_artwork_is_published'),
        ('exhibitions', '0004_remove_exhibition_artworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='exhibition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibition_artworks', to='exhibitions.exhibition', verbose_name='Выставка'),
        ),
    ]
