# Generated by Django 6.0.5 on 2026-07-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0016_artwork_exhibition'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Продано'),
        ),
    ]
